
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team02-m23-9am-2
owner: ucsb-cs156-m23
repo_name: team02-m23-9am-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-workflows-02-and-04","number":40,"title":"Pc fix workflows 02 and 04","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-2/pull/40"},{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"team02-Mohamed-HelpRequest-Tests","number":39,"title":"Team02 Mohamed help request tests","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-2/pull/39"},{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"team02-Mohamed-HelpRequest","number":38,"title":"Team02 Mohamed help request","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-2/pull/38"},{"author":{"id":"MDQ6VXNlcjM5ODM3OTM5","is_bot":false,"login":"cjyu81","name":"Charlie"},"headRefName":"Charlie-MenuItemReview","number":37,"title":"Charlie-Create menu item review database and corresponding methods","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-2/pull/37"}]
